#!/bin/bash

#------------------------------------------------------
# vimapi
#------------------------------------------------------
vimapi-cd() {
  local dir=${*:-$HOME}
  cd "$dir"
  vimapi.sh "lcd $PWD"
}

vimapi-pushd() {
  pushd "$@"
  vimapi.sh "lcd $PWD"
}

vimapi-popd() {
  popd "$@"
  vimapi.sh "lcd $PWD"
}

vimapi-dir() {
  local dir=${1:-$PWD}
  local winnr=${2:-1}
  vimapi.sh --winnr $winnr --edit-dir "$dir"
}

vimapi-dir2() {
  local dir=${1:-$PWD}
  local winnr=2
  vimapi.sh --winnr $winnr --edit-dir "$dir"
}

vimapi-vim() {
  local file="$1"
  local winnr=${2:--1}
  vimapi.sh --winnr $winnr --edit "$file"
}

vimapi-resize() {
  local rows=${1:-10}
  vimapi.sh VisWinResize $rows
}

vimapi-nerdtree() {
  local dir=${*:-$PWD}
  vimapi.sh VisNERDTreeFind "$dir/"
}

vimapi-fern() {
  local dir=${*:-$PWD}
  vimapi.sh VisFernDrawer "$dir/"
}

vimapi-termcd() {
  local winnr="$1"
  if [ -n "$winnr" ]; then
    vimapi.sh VisSendCdT2T "$PWD" $winnr
  fi
}

vimapi-tabline-set-label() {
  vimapi.sh VisTabLineSetLabel "$*"
}

vimapi-tabline-set-info() {
  vimapi.sh VisTabLineSetInfo "$*"
}

#------------------------------------------------------
# path
#------------------------------------------------------
vim_vis_plugin_dir() {
  sfile=$(realpath $BASH_SOURCE)
  sdir=${sfile%/*}
  echo ${sdir%/*}
}
export VIM_IDE_DIR=$(vim_vis_plugin_dir)
export PATH="$VIM_IDE_DIR/bin:$PATH"
