#!/bin/bash

#------------------------------------------------------
# vimapi
#------------------------------------------------------
vimapi-edit-file() {
  local file=$(pathconv.sh unix "$1")
  local winnr="${2:--1}"
  if [ -n "$file" ]; then
    vimapi.sh "call BmkEditFile('$file', $winnr)"
  fi
}

vimapi-edit-dir() {
  local dir="${1:-$PWD}"
  local dir=$(pathconv.sh unix "$dir")
  local winnr=${2:-1}
  if [ -n "$dir" ]; then
    vimapi.sh "call BmkEditDir('$dir/', $winnr)"
  fi
}

vimapi-edit-dir-2() {
  local dir="${1:-$PWD}"
  vimapi-edit-dir "$dir" 2
}

vimapi-cd() {
  local dir=${*:-$HOME}
  cd "$dir"
  vimapi.sh "lcd $PWD"
}

vimapi-pushd() {
  pushd "$@"
  vimapi.sh "lcd $PWD"
}

vimapi-popd() {
  popd "$@"
  vimapi.sh "lcd $PWD"
}

vimapi-resize() {
  local rows=${1:-10}
  vimapi.sh VisWinResize $rows
}

vimapi-termcd() {
  local winnr="$1"
  if [ -n "$winnr" ]; then
    vimapi.sh VisSendCdT2T "$PWD" $winnr
  fi
}

vimapi-term-set-label() {
  label=$(prompt.sh 'label' '' "$*")
  if [ -n "$label" ]; then
    vimapi.sh VisStatuslineForTermSetLabel "$label"
  fi
}

vimapi-tabline-set-label() {
  label=$(prompt.sh 'label' '' "$*")
  if [ -n "$label" ]; then
    vimapi.sh VisTabLineSetLabel "$label"
  fi
}

vimapi-tabline-set-info() {
  vimapi.sh VisTabLineSetInfo "$*"
}

#------------------------------------------------------
# path
#------------------------------------------------------
vim_vis_plugin_dir() {
  sfile=$(realpath $BASH_SOURCE)
  sdir=${sfile%/*}
  echo ${sdir%/*}
}

export VIM_IDE_DIR=$(vim_vis_plugin_dir)
export PATH="$VIM_IDE_DIR/bin:$PATH"
